=== szivos1/B9ZL3Q_XMLGyak/B9ZL3Q_1012/SZÁ_konyv1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="konyvek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="konyv">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" type="xs:string" />
                            <xs:element name="szerzo" type="xs:string" />
                            <xs:element name="szereplo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string" />
                                        <xs:element name="baratja" type="xs:string" />
                                        <xs:element name="szuletett" type="xs:string" />
                                        <xs:element name="jellemzes" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="masikszereplo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string" />
                                        <xs:element name="szuletett" type="xs:string" />
                                        <xs:element name="jellemzes" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
						<xs:attribute type="xs:string" name="isbn"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== szivos1/B9ZL3Q_XMLGyak/B9ZL3Q_1012/SZÁ_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SZÁ_konyv1.xsd">

<konyvek>   
    <konyv isbn="1">
        <cim>Mocskos Frédi a pilóta</cim>
        <szerzo>Rejtegető Ernő</szerzo>
        <szereplo>
            <nev>Fültől Dzsimi</nev>
            <baratja>Szúrós Balek</baratja>
            <szuletett>1968.04.04.</szuletett>
            <jellemzes>Vidám</jellemzes>
        </szereplo>
        <masikszereplo>
            <nev>Szúrós Balek</nev>
            <szuletett>1977.02.02.</szuletett>
            <jellemzes>Halott</jellemzes>
        </masikszereplo>
    </konyv>
	<konyv isbn="2">
        <cim>Csipke Rózsika</cim>
        <szerzo>Béla</szerzo>
        <szereplo>
            <nev>Rózsika</nev>
            <baratja>Orsó</baratja>
            <szuletett>1999.09.09.</szuletett>
            <jellemzes>Álmos</jellemzes>
        </szereplo>
        <masikszereplo>
            <nev>Orsó</nev>
            <szuletett>2001.01.01.</szuletett>
            <jellemzes>Szúr</jellemzes>
        </masikszereplo>
    </konyv>
</konyvek>
